TEMPORARY disable master tagging/gh pages publishing, enable workflow on current branch

diff --git a/.github/workflows/master.yml b/.github/workflows/master.yml
--- a/.github/workflows/master.yml
+++ b/.github/workflows/master.yml
@@ -3,74 +3,76 @@ on:
   push:
     branches:
       - 'master'
+      - 'build-and-push-docker-image-with-k-and-pyk' # FIXME remove after the test run
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
 
 jobs:
 
-  tag-release:
-    name: 'Tag Release and Bump Dependents'
-    runs-on: ubuntu-latest
-    steps:
-      - name: 'Check out code'
-        uses: actions/checkout@v3
-        with:
-          token: ${{ secrets.JENKINS_GITHUB_PAT }}
-          fetch-depth: 0
-      - name: Configure GitHub user
-        run: |
-          git config user.name devops
-          git config user.email devops@runtimeverification.com
-      - name: 'Update Version'
-        run: |
-          version=v"$(cat package/version)"
-          git tag --delete "${version}" || true
-          git push --delete origin "${version}" || true
-          git tag "${version}" HEAD
-          git push origin "${version}:${version}"
-      - name: 'Update dependents'
-        env:
-          GITHUB_TOKEN: ${{ secrets.JENKINS_GITHUB_PAT }}
-        run: |
-          version=v"$(cat package/version)"
-          curl --fail                                                          \
-            -X POST                                                            \
-            -H "Accept: application/vnd.github+json"                           \
-            -H "Authorization: Bearer ${GITHUB_TOKEN}"                         \
-            -H "X-GitHub-Api-Version: 2022-11-28"                              \
-            https://api.github.com/repos/runtimeverification/devops/dispatches \
-            -d '{"event_type":"on-demand-test","client_payload":{"repo":"runtimeverification/pyk","version":"'${version}'"}}'
+#FIXME uncomment after the test run
+  # tag-release:
+  #   name: 'Tag Release and Bump Dependents'
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: 'Check out code'
+  #       uses: actions/checkout@v3
+  #       with:
+  #         token: ${{ secrets.JENKINS_GITHUB_PAT }}
+  #         fetch-depth: 0
+  #     - name: Configure GitHub user
+  #       run: |
+  #         git config user.name devops
+  #         git config user.email devops@runtimeverification.com
+  #     - name: 'Update Version'
+  #       run: |
+  #         version=v"$(cat package/version)"
+  #         git tag --delete "${version}" || true
+  #         git push --delete origin "${version}" || true
+  #         git tag "${version}" HEAD
+  #         git push origin "${version}:${version}"
+  #     - name: 'Update dependents'
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.JENKINS_GITHUB_PAT }}
+  #       run: |
+  #         version=v"$(cat package/version)"
+  #         curl --fail                                                          \
+  #           -X POST                                                            \
+  #           -H "Accept: application/vnd.github+json"                           \
+  #           -H "Authorization: Bearer ${GITHUB_TOKEN}"                         \
+  #           -H "X-GitHub-Api-Version: 2022-11-28"                              \
+  #           https://api.github.com/repos/runtimeverification/devops/dispatches \
+  #           -d '{"event_type":"on-demand-test","client_payload":{"repo":"runtimeverification/pyk","version":"'${version}'"}}'
 
-  gh-pages:
-    name: Publish to GitHub Pages
-    runs-on: ubuntu-latest
-    needs: tag-release
-    steps:
-      - name: 'Check out code'
-        uses: actions/checkout@v3
-        with:
-          token: ${{ secrets.JENKINS_GITHUB_PAT }}
-          fetch-depth: 0
-      - name: Configure GitHub user
-        run: |
-          git config user.name devops
-          git config user.email devops@runtimeverification.com
-      - name: 'Install Poetry'
-        uses: Gr1N/setup-poetry@v8
-      - name: 'Build documentation'
-        run: make docs
-      - name: 'Push to gh-pages'
-        run: |
-          set -euxo pipefail
-          version=$(cat package/version)
-          git checkout gh-pages
-          find . -mindepth 1 -maxdepth 1 -not -name .git -not -name docs -exec rm -rf {} \;
-          cp -r docs/build/html/* .
-          rm -rf docs
-          touch .nojekyll
-          git add -A
-          git commit -m "gh-pages: update to v${version}" || true
-          git push
+  # gh-pages:
+  #   name: Publish to GitHub Pages
+  #   runs-on: ubuntu-latest
+  #   needs: tag-release
+  #   steps:
+  #     - name: 'Check out code'
+  #       uses: actions/checkout@v3
+  #       with:
+  #         token: ${{ secrets.JENKINS_GITHUB_PAT }}
+  #         fetch-depth: 0
+  #     - name: Configure GitHub user
+  #       run: |
+  #         git config user.name devops
+  #         git config user.email devops@runtimeverification.com
+  #     - name: 'Install Poetry'
+  #       uses: Gr1N/setup-poetry@v8
+  #     - name: 'Build documentation'
+  #       run: make docs
+  #     - name: 'Push to gh-pages'
+  #       run: |
+  #         set -euxo pipefail
+  #         version=$(cat package/version)
+  #         git checkout gh-pages
+  #         find . -mindepth 1 -maxdepth 1 -not -name .git -not -name docs -exec rm -rf {} \;
+  #         cp -r docs/build/html/* .
+  #         rm -rf docs
+  #         touch .nojekyll
+  #         git add -A
+  #         git commit -m "gh-pages: update to v${version}" || true
+  #         git push
 
   publish-docker:
     name: 'Publish docker image'
